version: "3.9"
services:
  qrls:
    build: .
    ports:
      - "3000:3000"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      DATABASE_URL: mongodb://root:test@mongo:27017/
  mongo:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test